spring:
  datasource:
    url: ${APP_DB_URL}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: ${APP_MAIL_HOST}
    port: ${APP_MAIL_PORT}
    username: ${APP_MAIL_USERNAME}
    password: ${APP_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: 3600000

server:
  servlet:
    session:
      cookie:
        secure: true

cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

client:
  url: ${CLIENT_URL}